repositories {
    google()
    mavenCentral()
}

configurations {
    testConf
}

dependencies {
    testConf("com.android.tools.build:gradle:8.7.3")
}

task resolve {
    doLast {
        configurations.testConf.resolvedConfiguration.resolvedArtifacts.each { artifact ->
            println "Resolved: ${artifact.file.absolutePath}"
        }
    }
}
